name: 'Medici CI - Slither'
description: 'Runs Slither on provided Solidity files'
inputs:
  contracts-path:
    description: 'Path to Solidity smart contract(s)'
  truffle-version:
    description: >
      The version of Truffle to run on the codebase, such as "truffle@5.0.0".
      Default is "truffle", which will use the latest.
    required: true
    default: 'truffle'
outputs:
  slither:
    description: 'Slither static analysis output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - {{ inputs.contracts-path }}
    - --truffle-version={{ inputs.truffle-version }}
    - --json
